main_opt_config:
    symbol: ["ETH/USDT", "GMX/USDT"]
    #  , 'NMR/USDT', 'MDT/USDT'
    start_point: ["2023-03-01"]
    period: ["1h"]
    limit: [505]


main_strat_config:
    length: [4, 5, 6, 7]
    multiplier: [4, 5, 6, 7]
    tpMultiplier: [1.06, 1.07, 1.04]
    slMultiplier: [0.93, 0.95, 0.97]